//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleOccasion
    {
        public int ArticleOccasionID { get; set; }
        public int Article { get; set; }
        public int Occasion { get; set; }
    
        public virtual Article Article1 { get; set; }
        public virtual Occasion Occasion1 { get; set; }
    }
}
