//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutfitAccessory
    {
        public int OutfitAccessoriesID { get; set; }
        public int Outfit { get; set; }
        public int Accessory { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Outfit Outfit1 { get; set; }
    }
}
