//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outfit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Outfit()
        {
            this.OutfitAccessories = new HashSet<OutfitAccessory>();
        }
    
        public int OutfitID { get; set; }
        public int Top { get; set; }
        public int Bottom { get; set; }
        public int Shoes { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Article Article1 { get; set; }
        public virtual Article Article2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutfitAccessory> OutfitAccessories { get; set; }
    }
}
