//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wardrobe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WardrobeEntities : DbContext
    {
        public WardrobeEntities()
            : base("name=WardrobeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArticleOccasion> ArticleOccasions { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Occasion> Occasions { get; set; }
        public virtual DbSet<OutfitAccessory> OutfitAccessories { get; set; }
        public virtual DbSet<Outfit> Outfits { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
